import { ABeeZee } from "next/font/google";
import "./globals.css";

const abeeZee = ABeeZee({
  variable: "--font-abeezee",
  subsets: ["latin"],
  weight: ["400"], // Light, Regular, and Bold
});
export const metadata = {
  title: "Promotions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${abeeZee.variable} antialiased`}>{children}</body>
    </html>
  );
}
